ALTER TABLE `users` COMMENT = '用户账号表',
  MODIFY COLUMN `id` varchar(36) NOT NULL COMMENT '用户ID',
  MODIFY COLUMN `email` varchar(255) NOT NULL COMMENT '登录邮箱',
  MODIFY COLUMN `password_hash` varchar(255) NOT NULL COMMENT '密码哈希',
  MODIFY COLUMN `status` varchar(32) NOT NULL COMMENT '用户状态：pending_verification、active、disabled',
  MODIFY COLUMN `email_verified_at` datetime COMMENT '邮箱验证时间',
  MODIFY COLUMN `created_at` datetime NOT NULL COMMENT '创建时间',
  MODIFY COLUMN `updated_at` datetime NOT NULL COMMENT '更新时间',
  MODIFY COLUMN `last_login_at` datetime COMMENT '最近登录时间',
  MODIFY COLUMN `is_deleted` boolean NOT NULL DEFAULT false COMMENT '软删除标识',
  MODIFY COLUMN `deleted_at` datetime COMMENT '删除时间';

ALTER TABLE `email_verification_tokens` COMMENT = '邮箱验证令牌表',
  MODIFY COLUMN `id` varchar(36) NOT NULL COMMENT '邮箱验证令牌ID',
  MODIFY COLUMN `user_id` varchar(36) NOT NULL COMMENT '用户ID',
  MODIFY COLUMN `token_hash` varchar(255) NOT NULL COMMENT '邮箱验证令牌哈希',
  MODIFY COLUMN `expires_at` datetime NOT NULL COMMENT '过期时间',
  MODIFY COLUMN `used_at` datetime COMMENT '使用时间',
  MODIFY COLUMN `created_at` datetime NOT NULL COMMENT '创建时间',
  MODIFY COLUMN `is_deleted` boolean NOT NULL DEFAULT false COMMENT '软删除标识',
  MODIFY COLUMN `deleted_at` datetime COMMENT '删除时间';

ALTER TABLE `password_reset_tokens` COMMENT = '密码重置令牌表',
  MODIFY COLUMN `id` varchar(36) NOT NULL COMMENT '密码重置令牌ID',
  MODIFY COLUMN `user_id` varchar(36) NOT NULL COMMENT '用户ID',
  MODIFY COLUMN `token_hash` varchar(255) NOT NULL COMMENT '密码重置令牌哈希',
  MODIFY COLUMN `expires_at` datetime NOT NULL COMMENT '过期时间',
  MODIFY COLUMN `used_at` datetime COMMENT '使用时间',
  MODIFY COLUMN `created_at` datetime NOT NULL COMMENT '创建时间',
  MODIFY COLUMN `is_deleted` boolean NOT NULL DEFAULT false COMMENT '软删除标识',
  MODIFY COLUMN `deleted_at` datetime COMMENT '删除时间';

ALTER TABLE `sessions` COMMENT = '登录会话表',
  MODIFY COLUMN `id` varchar(36) NOT NULL COMMENT '会话ID',
  MODIFY COLUMN `user_id` varchar(36) NOT NULL COMMENT '用户ID',
  MODIFY COLUMN `session_token_hash` varchar(255) NOT NULL COMMENT '会话令牌哈希',
  MODIFY COLUMN `expires_at` datetime NOT NULL COMMENT '过期时间',
  MODIFY COLUMN `created_at` datetime NOT NULL COMMENT '创建时间',
  MODIFY COLUMN `revoked_at` datetime COMMENT '撤销时间',
  MODIFY COLUMN `is_deleted` boolean NOT NULL DEFAULT false COMMENT '软删除标识',
  MODIFY COLUMN `deleted_at` datetime COMMENT '删除时间';

ALTER TABLE `resumes` COMMENT = '简历主表',
  MODIFY COLUMN `id` varchar(36) NOT NULL COMMENT '简历ID',
  MODIFY COLUMN `user_id` varchar(36) NOT NULL COMMENT '用户ID',
  MODIFY COLUMN `title` varchar(255) NOT NULL COMMENT '简历标题',
  MODIFY COLUMN `status` varchar(32) NOT NULL COMMENT '简历状态：generating、draft、published、failed、cancelled、deleted',
  MODIFY COLUMN `source_file_name` varchar(255) COMMENT '原始文件名',
  MODIFY COLUMN `source_file_type` varchar(16) COMMENT '原始文件类型：doc、docx、pdf',
  MODIFY COLUMN `source_file_size` int COMMENT '原始文件大小，单位字节',
  MODIFY COLUMN `current_task_id` varchar(36) COMMENT '当前生成任务ID',
  MODIFY COLUMN `is_deleted` boolean NOT NULL DEFAULT false COMMENT '软删除标识',
  MODIFY COLUMN `created_at` datetime NOT NULL COMMENT '创建时间',
  MODIFY COLUMN `updated_at` datetime NOT NULL COMMENT '更新时间',
  MODIFY COLUMN `deleted_at` datetime COMMENT '删除时间';

ALTER TABLE `resume_contents` COMMENT = '简历结构化内容表',
  MODIFY COLUMN `id` varchar(36) NOT NULL COMMENT '简历内容ID',
  MODIFY COLUMN `resume_id` varchar(36) NOT NULL COMMENT '简历ID',
  MODIFY COLUMN `content_json` json NOT NULL COMMENT '结构化简历内容JSON',
  MODIFY COLUMN `layout_json` json NOT NULL COMMENT '简历布局配置JSON',
  MODIFY COLUMN `created_at` datetime NOT NULL COMMENT '创建时间',
  MODIFY COLUMN `updated_at` datetime NOT NULL COMMENT '更新时间',
  MODIFY COLUMN `is_deleted` boolean NOT NULL DEFAULT false COMMENT '软删除标识',
  MODIFY COLUMN `deleted_at` datetime COMMENT '删除时间';

ALTER TABLE `resume_links` COMMENT = '在线简历链接表',
  MODIFY COLUMN `id` varchar(36) NOT NULL COMMENT '在线链接ID',
  MODIFY COLUMN `resume_id` varchar(36) NOT NULL COMMENT '简历ID',
  MODIFY COLUMN `slug` varchar(128) NOT NULL COMMENT '公开访问短标识',
  MODIFY COLUMN `access_mode` varchar(32) NOT NULL COMMENT '访问模式：public、private_link、password',
  MODIFY COLUMN `password_hash` varchar(255) COMMENT '访问密码哈希',
  MODIFY COLUMN `is_active` boolean NOT NULL COMMENT '链接是否有效',
  MODIFY COLUMN `created_at` datetime NOT NULL COMMENT '创建时间',
  MODIFY COLUMN `updated_at` datetime NOT NULL COMMENT '更新时间',
  MODIFY COLUMN `is_deleted` boolean NOT NULL DEFAULT false COMMENT '软删除标识',
  MODIFY COLUMN `deleted_at` datetime COMMENT '删除时间';

ALTER TABLE `generation_tasks` COMMENT = '简历生成任务表',
  MODIFY COLUMN `id` varchar(36) NOT NULL COMMENT '生成任务ID',
  MODIFY COLUMN `user_id` varchar(36) NOT NULL COMMENT '用户ID',
  MODIFY COLUMN `resume_id` varchar(36) NOT NULL COMMENT '简历ID',
  MODIFY COLUMN `file_type` varchar(16) NOT NULL COMMENT '上传文件类型：doc、docx、pdf',
  MODIFY COLUMN `file_size` int NOT NULL COMMENT '上传文件大小，单位字节',
  MODIFY COLUMN `temp_file_path` varchar(1024) NOT NULL COMMENT '临时文件路径',
  MODIFY COLUMN `status` varchar(32) NOT NULL COMMENT '任务状态：pending、parsing、ai_processing、completed、failed、cancelled、cleaned',
  MODIFY COLUMN `retry_count` int NOT NULL COMMENT '自动重试次数',
  MODIFY COLUMN `error_code` varchar(64) COMMENT '失败错误码',
  MODIFY COLUMN `error_message` varchar(1024) COMMENT '失败错误信息',
  MODIFY COLUMN `created_at` datetime NOT NULL COMMENT '创建时间',
  MODIFY COLUMN `updated_at` datetime NOT NULL COMMENT '更新时间',
  MODIFY COLUMN `completed_at` datetime COMMENT '完成时间',
  MODIFY COLUMN `is_deleted` boolean NOT NULL DEFAULT false COMMENT '软删除标识',
  MODIFY COLUMN `deleted_at` datetime COMMENT '删除时间';
